# Generated by Django 2.0.3 on 2020-04-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200421_0146'),
    ]

    operations = [
     
    
    ]
