# Generated by Django 2.0.3 on 2020-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
