# Generated by Django 2.0.3 on 2020-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200409_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.CharField(choices=[('clothers', 'Clothers'), ('accessores', 'Accessores'), ('shoes', 'Shoes')], default='clothers', max_length=25),
        ),
    ]
