# Generated by Django 2.0.3 on 2020-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_woman',
            field=models.BooleanField(default=False),
        ),
    ]
